### ISSUE TITLE
Potential re-designing storage APIs

### ISSUE THREAD

**Issue by LuZhang-Lou** [diem/off-chain-reference#105]
Today we have storage API in elegant pythonic styles (`__getitem__`, `__setitem__` etc). However the following functionality are not naively supported with this design:
1. allow users to shard data (no way to define sharding key)
2. allow async I/O to a. integrate with internal async APIs and b. improve I/O concurrency

Item 2 is related to data races and is related to this issue https://github.com/libra/off-chain-reference/issues/104. More specifically, we want to keep the APIs elegant but also eliminates the possibilities of race conditions, potentially by using locks. 

For Item 1, we discussed the options of sharding. It seems like we don't have a lot of wide selection of sharding keys: they need to be available in read path. Reference ID and storage key (the key we use in the k/v store) look like two good start points. We can also allow users to define the sharding algorithm/strategy. 

A side note is this may be a good chance to rethink how the storage layer works.

**Comment by gdanezis** [comment]
I think that your latest PR @LuZhang-Lou cover this issue. Should we close?
