### ISSUE TITLE
Will we allow partial updates to command?

### ISSUE THREAD

**Issue by LuZhang-Lou** [diem/off-chain-reference#107]
I have this question because `PaymentCommand.get_object()` takes `dependencies` (as base versions). As of today there does not seem to be actual partial updates to objects (as we avoid to do so). If we do not have plans in the future, maybe we don't need to load the dependencies at all ? 

https://github.com/libra/off-chain-reference/blob/master/src/offchainapi/payment_command.py#L46

**Comment by gdanezis** [comment]
That is an interesting point!
* You are right we currently do not create partial payments (although the mechanics for receiving those are in place where you are linking).
* However, the following lines a bit further down:

            # Need to get a deepcopy new version.
            updated_payment = dep_object.new_version(new_version)
            PaymentObject.from_full_record(
                self.command, base_instance=updated_payment)

Implement all the logic for the constraint check in `from_full_record` -- ie. what fields can up updated, etc.

So if we remove the dependencies here, we would need to have a separate place with access to the old and new payment that would compare them to ensure our constraints are satisfied.
